### ISSUE TITLE
Question: How to obtain hash

### ISSUE THREAD

**Issue by probablyjassin** [Schrankian/campus-dual-app#12]
Hi, I'm trying to understand how the "hash" property that is used in various campusdual-api-requests, is constructed. Currently I'm just using my hash directly, but I would like to be able to use my username and password for my login procedure.

If you happened to know how that works that'd be amazing.

**Comment by Schrankian** [comment]
Hey, the hash is calculated by campus-dual, so i wasn't able to figure out how to build this hash myself. But as you probably already know, the hash can be found in a html script tag once a user has logged in. So I reverse engineered the login procedure to get the login cookie, which then can be used to impersonate the user. The whole code related to the campus-dual scraping is located in this [file](https://github.com/Schrankian/campus-dual-app/blob/main/lib/scripts/campus_dual_manager.dart).
But basically it's the following two steps:

1. Get the XSRF-Token (Which is there to prevent Cross-Site-Request-Forgery)
```dart
final Uri loginUri = Uri.parse("https://erp.campus-dual.de/sap/bc/webdynpro/sap/zba_initss?sap-client=100&sap-language=de&uri=https%3a%2f%2fselfservice.campus-dual.de%2findex%2flogin");

CookieClient session = CookieClient();

// Initial request to get the login page
final initResponse = await session.get(loginUri, headers: stdHeaders);
if (initResponse.statusCode != 200) {
    throw Exception("Failed to initialize the login session");
}

// Parse the response and get the XSRF token
final doc = parse(initResponse.body);
// Get the XSRF token. Hint: The token hides in an hidden input field
final xsrfToken = doc.querySelector("input[name='sap-login-XSRF']")?.attributes["value"];
if (xsrfToken == null) {
      throw Exception("Failed to get the XSRF token");
}
```
2. Use this token to log in using username and password

```dart
// Request to login and get the session cookie
final loginResponse = await session.post(
loginUri,
headers: stdHeaders,
body: {
    "FOCUS_ID": "sap-user",
    "sap-system-login-oninputprocessing": "onLogin",
    "sap-urlscheme": "",
    "sap-system-login": "onLogin",
    "sap-system-login-basic_auth": "",
    "sap-client": "100",
    "sap-language": "DE",
    "sap-accessibility": "",
    "sap-login-XSRF": xsrfToken,
    "sap-system-login-cookie_disabled": "",
    "sap-user": username ?? userCreds!.username,
    "sap-password": password ?? userCreds!.password,
    "SAPEVENTQUEUE": "Form_Submit~E002Id~E004SL__FORM~E003~E002ClientAction~E004submit~E005ActionUrl~E004~E005ResponseData~E004full~E005PrepareScript~E004~E003~E002~E003"
      },
    );

if (loginResponse.statusCode != 302 || loginResponse.body.contains("loginForm")) {
    throw Exception("Failed to login");
}

return session; // This session contains the "MYSAPSSO2" Cookie, which is used to authenticated to the campus-dual servers when requesting the actual html pages
```
(3. Get the hash using the created session)
```dart
final doc = await _scrape(session, "https://selfservice.campus-dual.de/index/login");

final scriptTag = doc.querySelector("#main")?.querySelector("script")!.innerHtml;

final hashRegExp = RegExp(r'hash="([^"]*)"');
final match = hashRegExp.firstMatch(scriptTag!);

if (match != null && match.groupCount > 0) {
    final hash = match.group(1)!;
    return hash;
} else {
    throw Exception("Failed to scrape hash");
}
```

So yeah that's basically it. You can just execute it everytime you need the hash and then cache it for subsequent requests. 

Hope this helps you :)

**Comment by probablyjassin** [comment]
Yo thank you so much! I'll look into this and try to adapt it. 

By the way has your hash ever expired/changed? After how long would that happen? Mine hasn't changed ever since I first got it (1 week ago).

**Comment by Schrankian** [comment]
Glad I could help. I actually prototyped this in Javascript but I deleted the code for that (-‿-"). Using JavaScript won’t make a big difference—you just need a way to handle cookies and parse the returned HTML, which shouldn’t be an issue since JavaScript is practically made for these tasks. There are also a lot of well-documented packages out there that do exactly that.

As for the hash, it’s likely just a combination of the username, password, and some salt, so I wouldn’t expect it to change. My hash has stayed the same for over two years now, and it’ll probably stay that way unless they decide to update the backend.

**Comment by Schrankian** [comment]
Yeah doing it frontend-only might not work without using some hacks. I tried a few different things myself, but in the end got defeated by CORB, because campus-dual doesn't seem to have set up any CORS.
Writing a backend is easy as long as you just use it for yourself, because if you open it to the public you will have all data, including credentials, going through your server which will open some security concerns.
The proxy one might work with some additional configuration, but it also has some security concerns so it needs to be properly secured.
Apart from these ideas, i don't think theres another way of doing this, so either you find a way to bypass CORB or you have to write your own Backend or Proxy.
